"""
Simulated activity generator for fact_activities.

Route selection logic by affinity:
- activity_match: higher weight if route matches user's preferred activity
- exp_diff_matrix: weight based on experience-difficulty match
- home_zone: higher weight if route is in a user's home zone

Volumes and distributions controlled by config.py.
"""

import csv
import math
import random
from datetime import timedelta

from src.config import (
    ABANDON_RATE,
    ACTIVITIES_LOGNORMAL_MU,
    ACTIVITIES_LOGNORMAL_SIGMA,
    AFFINITY_ACTIVITY_MATCH,
    AFFINITY_ACTIVITY_NO_MATCH,
    AFFINITY_EXP_DIFF_MATRIX,
    AFFINITY_HOME_ZONE,
    AFFINITY_OTHER_ZONE,
    DATA_RAW_DIR,
    DATE_END,
    DURATION_EXPERIENCE_FACTOR,
    NUM_HOME_ZONES,
    RATING_MEAN_ABANDONED,
    RATING_MEAN_COMPLETED,
    RATING_PROBABILITY,
    RATING_STD_ABANDONED,
    RATING_STD_COMPLETED,
    SEED,
    TARGET_ACTIVITIES,
    WEEKEND_PROBABILITY,
    ZONE_IDS,
)


def generate_activities(users, routes, seed=SEED):
    """Generate ~TARGET_ACTIVITIES activities with user-route affinity.

    Args:
        users: list of dicts generated by generate_users()
        routes: list of dicts generated by generate_routes()

    Returns:
        list[dict]: List of dicts with fact_activities fields.
    """
    random.seed(seed)

    zone_id_list = list(ZONE_IDS.values())

    # Index routes by id for fast access
    routes_by_id = {r["route_id"]: r for r in routes}
    route_ids = [r["route_id"] for r in routes]

    # Step 1: determine num_activities per user (lognormal)
    raw_counts = []
    for _ in users:
        raw = random.lognormvariate(ACTIVITIES_LOGNORMAL_MU, ACTIVITIES_LOGNORMAL_SIGMA)
        raw_counts.append(max(1, min(200, int(raw))))

    # Scale so total approaches TARGET_ACTIVITIES
    total_raw = sum(raw_counts)
    scale_factor = TARGET_ACTIVITIES / total_raw
    user_counts = [max(1, round(c * scale_factor)) for c in raw_counts]

    # Step 2: assign home zones per user (1-3 zones)
    user_home_zones = {}
    for u in users:
        n_homes = random.randint(NUM_HOME_ZONES[0], NUM_HOME_ZONES[1])
        user_home_zones[u["user_id"]] = random.sample(zone_id_list, n_homes)

    # Step 3: pre-compute affinity weights per user
    activities = []
    activity_id = 1

    for user_idx, user in enumerate(users):
        uid = user["user_id"]
        n_acts = user_counts[user_idx]
        pref_act = user["preferred_activity_type_id"]
        exp_level = user["experience_level"]
        reg_date_str = user["registration_date"]

        # Parse registration date
        from datetime import date as date_cls
        reg_parts = reg_date_str.split("-")
        reg_date = date_cls(int(reg_parts[0]), int(reg_parts[1]), int(reg_parts[2]))

        home_zones = user_home_zones[uid]

        # Compute affinity weights for each route
        weights = []
        for route in routes:
            # Activity match
            if pref_act != "" and route["activity_type_id"] == pref_act:
                w_act = AFFINITY_ACTIVITY_MATCH
            else:
                w_act = AFFINITY_ACTIVITY_NO_MATCH

            # Experience-difficulty match
            w_exp = AFFINITY_EXP_DIFF_MATRIX.get(
                (exp_level, route["difficulty"]), 1.0
            )

            # Home zone
            if route["zone_id"] in home_zones:
                w_zone = AFFINITY_HOME_ZONE
            else:
                w_zone = AFFINITY_OTHER_ZONE

            weights.append(w_act * w_exp * w_zone)

        # Generate n_acts activities for this user
        days_available = (DATE_END - reg_date).days
        if days_available <= 0:
            days_available = 1

        for _ in range(n_acts):
            # Select route by affinity weights
            chosen_route = random.choices(routes, weights=weights, k=1)[0]

            # Activity date: post-registration, with weekend bias
            activity_date = _random_date_with_weekend_bias(reg_date, days_available)

            # Completed vs abandoned
            abandon_key = (exp_level, chosen_route["difficulty"])
            abandon_rate = ABANDON_RATE.get(abandon_key, 0.05)
            completed = random.random() >= abandon_rate

            # Actual duration: estimated * experience_factor * noise
            exp_factor = DURATION_EXPERIENCE_FACTOR[exp_level]
            noise = random.gauss(1.0, 0.15)
            estimated = chosen_route["estimated_duration_h"]
            if not completed:
                # Abandoned: 30-80% of estimated duration
                actual_duration = estimated * exp_factor * noise * random.uniform(0.3, 0.8)
            else:
                actual_duration = estimated * exp_factor * noise
            actual_duration = round(max(0.2, actual_duration), 1)

            # Rating: 60% probability if completed, lower if abandoned
            rating = _generate_rating(completed)

            activities.append({
                "activity_id": activity_id,
                "user_id": uid,
                "route_id": chosen_route["route_id"],
                "activity_date": activity_date.isoformat(),
                "completed": int(completed),
                "actual_duration_h": actual_duration,
                "rating": rating if rating is not None else "",
            })
            activity_id += 1

    # Write CSV
    DATA_RAW_DIR.mkdir(parents=True, exist_ok=True)
    csv_path = DATA_RAW_DIR / "activities.csv"
    fieldnames = [
        "activity_id", "user_id", "route_id", "activity_date",
        "completed", "actual_duration_h", "rating",
    ]
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(activities)

    _print_stats(activities, users, routes)
    return activities


def _random_date_with_weekend_bias(start_date, max_days):
    """Generate a random date with weekend bias.

    First decides if it's a weekend (using WEEKEND_PROBABILITY),
    then picks a random date of that type within range.
    """
    want_weekend = random.random() < WEEKEND_PROBABILITY

    for _ in range(50):
        offset = random.randint(0, max_days)
        d = start_date + timedelta(days=offset)
        is_weekend = d.weekday() >= 5
        if is_weekend == want_weekend:
            return d

    # Fallback: return any date in range
    return start_date + timedelta(days=random.randint(0, max_days))


def _generate_rating(completed):
    """Generate rating (1-5) with different probability and mean based on completion."""
    if random.random() > RATING_PROBABILITY:
        return None

    if completed:
        rating = random.gauss(RATING_MEAN_COMPLETED, RATING_STD_COMPLETED)
    else:
        rating = random.gauss(RATING_MEAN_ABANDONED, RATING_STD_ABANDONED)

    return max(1, min(5, round(rating)))


def _print_stats(activities, users, routes):
    """Print statistics of generated activities."""
    n = len(activities)
    print(f"\n--- Activities: {n} generated ---")

    # Completed
    completed = sum(1 for a in activities if a["completed"])
    print(f"  Completed: {completed} ({completed/n*100:.1f}%)")

    # With rating
    rated = sum(1 for a in activities if a["rating"] != "")
    print(f"  With rating: {rated} ({rated/n*100:.1f}%)")

    if rated > 0:
        ratings = [a["rating"] for a in activities if a["rating"] != ""]
        avg_rating = sum(ratings) / len(ratings)
        print(f"  Avg rating: {avg_rating:.2f}")

    # Rating distribution
    rating_counts = {}
    for a in activities:
        if a["rating"] != "":
            rating_counts[a["rating"]] = rating_counts.get(a["rating"], 0) + 1
    if rating_counts:
        print("  Rating distribution:")
        for r in sorted(rating_counts.keys()):
            count = rating_counts[r]
            print(f"    {r}: {count:5d} ({count/rated*100:5.1f}%)")

    # Activities per user: min, max, mean, median
    user_act_counts = {}
    for a in activities:
        uid = a["user_id"]
        user_act_counts[uid] = user_act_counts.get(uid, 0) + 1
    counts = sorted(user_act_counts.values())
    print(f"  Activities/user: min={counts[0]}, max={counts[-1]}, "
          f"mean={sum(counts)/len(counts):.1f}, median={counts[len(counts)//2]}")

    # Unique routes used
    unique_routes = len(set(a["route_id"] for a in activities))
    print(f"  Unique routes used: {unique_routes}/{len(routes)}")

    # Weekend ratio
    weekend = sum(1 for a in activities
                  if _parse_date(a["activity_date"]).weekday() >= 5)
    print(f"  Weekend: {weekend/n*100:.1f}%")

    print(f"  CSV: data/raw/activities.csv")


def _parse_date(date_str):
    from datetime import date as date_cls
    parts = date_str.split("-")
    return date_cls(int(parts[0]), int(parts[1]), int(parts[2]))
